### ISSUE TITLE
The extension is not working

### ISSUE THREAD

**Issue by yukina3230** [swinzy/auto-brightness-toggle#1]
When I click on the Auto Brightness toggle button, nothing happens. I don't know if it needs anything else to work.
I'm using Arch Linux and Gnome 43.

**Comment by swinzy** [comment]
Could you verify in your `Gnome Settings` -> `Power`, the option `Automatic Screen Brightness` is available?

**Comment by yukina3230** [comment]
It doesn't show in my Settings
![image](https://user-images.githubusercontent.com/75545944/217299721-420d7504-62f0-481c-a04e-0841a47e98c2.png)

**Comment by swinzy** [comment]
> It doesn't show in my Settings

If this is the case, that means your system (software or hardware) doesn't support auto brightness. 
I haven't added the code to detect system compatibility (will add later this week).
Are you using a laptop with such function? If so, maybe check if your GPU driver is properly installed and configured.

**Comment by swinzy** [comment]
Basically what this extension does is to be synced to that system option I mentioned about. If that option isn't available, this extension won't work. 

~Ideally it shouldn't show up in your quick panel but I'm working on that part.~
Update: I've added the function of detecting if auto brightness is available for you or not. Now after you update the extension and enable it, if you see the option greyed out, that means your computer doesn't support auto brightness. :)

**Comment by swinzy** [comment]
Hi, new version is published. If you have updated your GNOME since then. You may have a try of that. Let me know if problem still exists :)
