### ISSUE TITLE
One-shot auto brightness

### ISSUE THREAD

**Issue by hensnenenej** [swinzy/auto-brightness-toggle#6]
This is a nice extension, but what would make it really great - is a setting for one-shot auto brightness, that is turn on auto brightness for a second on screen powering on, and then turn it off. Such setting is present on some android smartphones, and it's really useful for people who used to control brightness manually, but frequently puts their devices to sleep in one place and turns it on in another.

**Comment by swinzy** [comment]
Sounds reasonably useful. Will consider! Thanks for your suggestion!

**Comment by swinzy** [comment]
Hi @hensnenenej,

I have added the feature you suggested and have uploaded the new version on to extensions.gnome.org.

Do note that how brightness level is determined is up to GNOME and the data returned from device sensors. I can't guarantee that the brightness level would be ideal when the one shot auto brightness activates.

Thanks for your suggestion!
Stephen
